### ISSUE TITLE
Please merge the Pull Request to serialize datetime.date

### ISSUE THREAD

**Issue by mkmoisen** [irmen/Serpent#16]
Hi Irmen,

Serpent fails to serialize datetime.date objects:

    >>> import serpent
    >>> import datetime
    >>> serpent.dumps(datetime.date.today())
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "build/bdist.linux-x86_64/egg/serpent.py", line 78, in dumps
      File "build/bdist.linux-x86_64/egg/serpent.py", line 250, in serialize
      File "build/bdist.linux-x86_64/egg/serpent.py", line 291, in _serialize
      File "build/bdist.linux-x86_64/egg/serpent.py", line 551, in ser_default_class
    TypeError: don't know how to serialize class <type 'datetime.date'>. Give it vars() or an appropriate __getstate__

[My pull request](https://github.com/irmen/Serpent/pull/15) adds the appropriate method and unit tests. Would you please review and merge it soon? Logistically, when would pip have the latest build if you chose to merge this?

Thanks and best regards. --Matthew Moisen

**Comment by irmen** [comment]
I'll have a look soon, expect a new release somewhere in the coming weekend.

**Comment by irmen** [comment]
.... why did I forget about this class in the first place, I included serializers for the other types in the datetime module....

**Comment by irmen** [comment]
That was a simple clean patch, thank you. New version is up on pypi.

**Comment by mkmoisen** [comment]
Awesome, thank you Irmen.
