### ISSUE TITLE
uuid.UUID objects are not correctly loaded

### ISSUE THREAD

**Issue by ClaymorePT** [irmen/Serpent#27]
@irmen  serpent is not correctly deserializing  the uuid.UUID object. It returns a string instead of an UUID object.
The following code reproduces the issue.

```
>>> import uuid
>>> import serpent
>>> x = uuid.uuid4()
>>> b = serpent.dumps(x)
>>> y = serpent.loads(b)
>>> y == x
False
>>> type(y)
<class 'str'>
```

**Comment by irmen** [comment]
Umm. yes, that is intentional. Serpent creates Python literal expressions and a uuid object is not one of the objects you can create in Python with a literal expression.
The best we can do is to serialize it into a string form, as described https://github.com/irmen/Serpent#some-more-details

**Comment by ClaymorePT** [comment]
@irmen  Is it possible for me to override the serializer and deserielizer for uuid.UUID class?

This is creating issues to me, because I also use PyRO and my remote methods are expecting UUID objects, and it would be a performance-kill to add more logic to support strings.

**Comment by irmen** [comment]
Yes you can override this.

But there's no way around the uuid traveling as a string over the wire, because it has to be in literal expression format when using serpent. So either recognize this fact in your remote methods, and let them convert it back to a proper uuid object, or write a serialization override. The uuid->str->uuid conversion is taking place either way.

You'll have to override it on the Pyro level because Serpent cannot and will not deserialize into custom classes.  See http://pyro4.readthedocs.io/en/stable/clientcode.html?highlight=register_class_to_dict#changing-the-way-your-custom-classes-are-de-serialized      you'll need to register a _to_dict function in your clients, and a _to_class function in your server.

**Comment by ClaymorePT** [comment]
@irmen  Ok. Thank you for the assistance. I will look into the docs.

**Comment by irmen** [comment]
👍 just write if you require some more help this is a lowlevel Pyro feature

**Comment by ClaymorePT** [comment]
@irmen  I'm still having some issues in serialising the UUID class.

Shouldn't this be enough to override the default serialization of UUIDs ?
```
SerializerBase.register_dict_to_class("uuid.UUID", (lambda cls, data: uuid.UUID(bytes=data[0])))
SerializerBase.register_class_to_dict(UUID, (lambda obj: {"__class__": "uuid.UUID", 0: obj.bytes}))
```

**Comment by irmen** [comment]
Did you switch to json serialization? I thought you were using serpent earlier

**Comment by ClaymorePT** [comment]
I did. I tried them all. json, serpent, msgpack and pickle. The problem with pickle is that I'm unable to properly define remote exceptions, due to their module path.

Still, even when using serpent, shouldn't this code be enough to properly deserialize UUIDs ?
```
SerializerBase.register_dict_to_class("uuid.UUID", (lambda cls, data: uuid.UUID(int=int(data["d"]))))
SerializerBase.register_class_to_dict(uuid.UUID, (lambda obj: {"__class__": "uuid.UUID", "d": int(obj)}))
```
Or am I missing something?

**Comment by irmen** [comment]
No, that is exactly how it works. So I really don't know what the problem is you're running into? Have you looked ad the ser_custom example? In any case, here are a client and server program that use the custom uuid serialization you described above, in a symmetric manner, and are working just fine.

```
# client.py
import uuid
import Pyro4
from Pyro4.util import SerializerBase


SerializerBase.register_dict_to_class("uuid.UUID", (lambda cls, data: uuid.UUID(int=int(data["d"]))))
SerializerBase.register_class_to_dict(uuid.UUID, (lambda obj: {"__class__": "uuid.UUID", "d": int(obj)}))


with Pyro4.Proxy("PYRONAME:test.seruuid") as p:
    response = p.process(uuid.uuid4())
    print("response:", repr(response))
```
and

```
# server.py 
import uuid
import Pyro4
from Pyro4.util import SerializerBase


SerializerBase.register_dict_to_class("uuid.UUID", (lambda cls, data: uuid.UUID(int=int(data["d"]))))
SerializerBase.register_class_to_dict(uuid.UUID, (lambda obj: {"__class__": "uuid.UUID", "d": int(obj)}))


class Service:
    @Pyro4.expose
    def process(self, thing):
        print("got:", repr(thing))
        return uuid.uuid4()


Pyro4.Daemon.serveSimple({
    Service: "test.seruuid"
})
```

**Comment by ClaymorePT** [comment]
@irmen 
Yeah, your example is working. Somewhere along the line, I must have done something wrong. 
It is now working well.

Just one thing. I was now trying to optimise the UUID example, and instead of serializing into an int, I was trying to serialize into bytes.  But an error appeared.

Using 
```
SerializerBase.register_dict_to_class("uuid.UUID", (lambda cls, data: uuid.UUID(bytes=data['d'])))
SerializerBase.register_class_to_dict(uuid.UUID, (lambda obj: {"__class__": "uuid.UUID", 'd': obj.bytes}))
```
This happened

```
Traceback (most recent call last):
  File "client.py", line 19, in <module>
    response = p.process(uuid.uuid4())
  File "/usr/lib/python3.6/site-packages/Pyro4/core.py", line 187, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/lib/python3.6/site-packages/Pyro4/core.py", line 472, in _pyroInvoke
    raise data  # if you see this in your traceback, you should probably inspect the remote traceback as well
ValueError: bytes is not a 16-char string
```

Is it possible to serialise bytes using serpent?

**Comment by irmen** [comment]
Have you tried what happens when you do?
Like uuids, there is no direct 1:1 roundtrip for bytes because serpent is a text based protocol. As stated in the readme "bytes, bytearrays, memoryview, buffer --> string, base-64 (you'll have to manually un-base64 them though. Can use serpent.tobytes function)"
The valueerror exception you're seeing is thrown by the uuid constructor method because it's receiving the base64 encoded dictionary form of the bytes.

You can debug all this by enabling the logging and wire tracing of Pyro btw

**Comment by ClaymorePT** [comment]
@irmen  Ok. Thanks for the support! This is enough for me to continue. Thank you!

**Comment by ClaymorePT** [comment]
@irmen  
If I try your code, I get the same thing. 
For what I can tell, it is preferable to convert the uuid to int instead of bytes. The output is smaller.


Ok, thank you for your support. With what I gathered, I can now continue my work :) thank you!

**Comment by ClaymorePT** [comment]
@irmen 

One last question. It hasn't anything to do with this topic.

I'm having lots of "handshake failed" messages with the debug output.
```
connected ('192.168.100.2', 54614) - unencrypted
handshake failed, connection closed early
connected ('192.168.100.2', 54618) - unencrypted
handshake failed, connection closed early
connected ('192.168.100.2', 54622) - unencrypted
handshake failed, connection closed early
```

Do you have any hint on what might be causing this? This happens when there's nothing happening.

**Comment by irmen** [comment]
That looks like a port scanner being active on your network that is trying to connect to the port you're hosting your Pyro daemon on....?

**Comment by ClaymorePT** [comment]
That is weird. It's in isolated network (virtual network) and the logout is comming from the client side, not the server. 
Is it possible for a Pyro proxy to remain in a continued state where it keeps trying to establish a session with a Pyro Daemon?

**Comment by irmen** [comment]
Pyro's not doing that by itself, must be something in your own client code. Even the automatic reconnect feature requires *some* client code intervention.

**Comment by ClaymorePT** [comment]
@irmen 
It seems that it's the Autoclean feature from the Nameserver that is trying to connect to the Pyro daemon. I just don't know yet why is it failing the handshake.
Is it because a connection is sufficient for the nameserver to be sure that the Pyro Daemon is still active?

**Comment by irmen** [comment]
Ah yes, see https://github.com/irmen/Pyro4/blob/master/src/Pyro4/naming.py#L351
If this is problematic, don't enable the ns autoclean.

If there's something else, please head over to the Pyro4 issue tracker rather than continuing here, because these issues have nothing to do with Serpent itself :)

**Comment by ClaymorePT** [comment]
@irmen Thank you!

**Comment by irmen** [comment]
btw the bunch of handshake failed errors in the log is not as clean as I would like, maybe I can improve this in a future Pyro4 release

**Comment by ClaymorePT** [comment]
@irmen  Ok. For me, the excess doesn't seem to be an issue. 

Instead of initiating an entire TCP session, may I sugest to implement a simple ping-pong mechanism, just to check if there is an active Daemon on the other side. I think it would be enough.

**Comment by ClaymorePT** [comment]
@irmen  Starting a TCP session is more costly to the network and to the system, than just sending two or three UDP specially tailored packets.
Having the Pyro Daemon listening for those packets with a UDP socket, and answering right back, would be simpler and lighter to the network.

**Comment by irmen** [comment]
I dunno, that would require all Pyro daemons to create and listen on a second server socket for those udp messages next to the regular socket they have now...  

Again, if this bothers you, head over to the Pyro4 issue tracker to discuss this further, instead of here.

**Comment by ClaymorePT** [comment]
@irmen  No need. I will wait for your solution when you have the time to implement it in a future release.
It doesn't bother me since this is the result of having the log in debug mode.

Once again, thank you for your support.
