### ISSUE TITLE
Python 3.11 test failures

### ISSUE THREAD

**Issue by frantisekz** [irmen/Serpent#40]
There are a few test failures on Python 3.11, mainly due to missing __class__:

```
testAttr (test_serpent.DataclassesTests.testAttr) ... FAIL
test_array (test_serpent.TestBasics.test_array) ... ok
test_bool (test_serpent.TestBasics.test_bool) ... ok
test_bytes (test_serpent.TestBasics.test_bytes) ... ok
test_class (test_serpent.TestBasics.test_class) ... FAIL
test_class2 (test_serpent.TestBasics.test_class2) ... ERROR
test_class_hashable_key_check (test_serpent.TestBasics.test_class_hashable_key_check) ... ok
test_class_hashable_set_element_check (test_serpent.TestBasics.test_class_hashable_set_element_check) ... ok
test_comments (test_serpent.TestBasics.test_comments) ... ok
test_detectNullByte (test_serpent.TestBasics.test_detectNullByte) ... ok
test_dict (test_serpent.TestBasics.test_dict) ... ok
test_dict_iters (test_serpent.TestBasics.test_dict_iters) ... ok
test_dict_str (test_serpent.TestBasics.test_dict_str) ... ok
test_enum_hashable (test_serpent.TestBasics.test_enum_hashable) ... ok
test_enums (test_serpent.TestBasics.test_enums) ... ok
test_exception (test_serpent.TestBasics.test_exception) ... ok
test_exception2 (test_serpent.TestBasics.test_exception2) ... ok
test_float_precision (test_serpent.TestBasics.test_float_precision) ... ok
test_header (test_serpent.TestBasics.test_header) ... ok
test_list (test_serpent.TestBasics.test_list) ... ok
test_none (test_serpent.TestBasics.test_none) ... ok
test_nullbytesstr (test_serpent.TestBasics.test_nullbytesstr) ... ok
test_nullbytesstring (test_serpent.TestBasics.test_nullbytesstring) ... ok
test_numbers (test_serpent.TestBasics.test_numbers) ... ok
test_pickle_api (test_serpent.TestBasics.test_pickle_api) ... ok
test_py2_py3_unicode_repr (test_serpent.TestBasics.test_py2_py3_unicode_repr) ... ok
test_set (test_serpent.TestBasics.test_set) ... ok
test_sorting (test_serpent.TestBasics.test_sorting) ... ok
test_string (test_serpent.TestBasics.test_string) ... ok
test_string_with_escapes (test_serpent.TestBasics.test_string_with_escapes) ... ok
test_time (test_serpent.TestBasics.test_time) ... ok
test_timezone (test_serpent.TestBasics.test_timezone) ... ok
test_tobytes (test_serpent.TestBasics.test_tobytes) ... ok
test_tuple (test_serpent.TestBasics.test_tuple) ... ok
test_unicode_U (test_serpent.TestBasics.test_unicode_U) ... ok
test_unicode_escape_allchars (test_serpent.TestBasics.test_unicode_escape_allchars) ... ok
test_unicode_quotes (test_serpent.TestBasics.test_unicode_quotes) ... ok
test_unicode_with_escapes_py3 (test_serpent.TestBasics.test_unicode_with_escapes_py3) ... ok
test_utf8_correctness (test_serpent.TestBasics.test_utf8_correctness) ... ok
test_weird_floats (test_serpent.TestBasics.test_weird_floats) ... ok
testChainMap (test_serpent.TestCollections.testChainMap) ... FAIL
testCounter (test_serpent.TestCollections.testCounter) ... ok
testDefaultDict (test_serpent.TestCollections.testDefaultDict) ... ok
testDeque (test_serpent.TestCollections.testDeque) ... ok
testNamedTuple (test_serpent.TestCollections.testNamedTuple) ... ok
testOrderedDict (test_serpent.TestCollections.testOrderedDict) ... ok
testUserDict (test_serpent.TestCollections.testUserDict) ... ok
testUserList (test_serpent.TestCollections.testUserList) ... ok
testUserString (test_serpent.TestCollections.testUserString) ... ok
testCustomClass (test_serpent.TestCustomClasses.testCustomClass) ... ok
testRegisterOrderPreserving (test_serpent.TestCustomClasses.testRegisterOrderPreserving) ... ok
testSubclass (test_serpent.TestCustomClasses.testSubclass) ... ok
testUUID (test_serpent.TestCustomClasses.testUUID) ... ok
testClassCycle (test_serpent.TestCyclic.testClassCycle) ... ok
testDictCycle (test_serpent.TestCyclic.testDictCycle) ... ok
testDictOk (test_serpent.TestCyclic.testDictOk) ... ok
testListCycle (test_serpent.TestCyclic.testListCycle) ... ok
testListOk (test_serpent.TestCyclic.testListOk) ... ok
testMaxLevel (test_serpent.TestCyclic.testMaxLevel) ... ok
testTupleOk (test_serpent.TestCyclic.testTupleOk) ... ok
test_deserialize (test_serpent.TestDeserialize.test_deserialize) ... ok
test_deserialize_chr (test_serpent.TestDeserialize.test_deserialize_chr) ... ok
test_input_types (test_serpent.TestDeserialize.test_input_types) ... ok
test_trailing_comma_set (test_serpent.TestDeserialize.test_trailing_comma_set) ... ok
test_trailing_commas (test_serpent.TestDeserialize.test_trailing_commas) ... ok
test_unicode_escapes (test_serpent.TestDeserialize.test_unicode_escapes) ... ok
test_weird_complex (test_serpent.TestDeserialize.test_weird_complex) ... ok
testFile (test_serpent.TestFiledump.testFile) ... ok
test_indent_containers (test_serpent.TestIndent.test_indent_containers) ... ok
test_indent_primitive (test_serpent.TestIndent.test_indent_primitive) ... ok
test_indent_sorting (test_serpent.TestIndent.test_indent_sorting) ... ok
testIntercept (test_serpent.TestInterceptClass.testIntercept) ... ok
testRegular (test_serpent.TestInterceptClass.testRegular) ... ERROR
testException (test_serpent.TestPyro4.testException) ... ok
test_deser_speed (test_serpent.TestSpeed.test_deser_speed) ... skipped 'no performance tests in default test suite'
test_ser_speed (test_serpent.TestSpeed.test_ser_speed) ... skipped 'no performance tests in default test suite'
======================================================================
ERROR: test_class2 (test_serpent.TestBasics.test_class2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/serpent-1.30.2/tests/test_serpent.py", line 516, in test_class2
    self.assertEqual('pprint.PrettyPrinter', data["__class__"])
                                             ~~~~^^^^^^^^^^^^^
KeyError: '__class__'
======================================================================
ERROR: testRegular (test_serpent.TestInterceptClass.testRegular)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/serpent-1.30.2/tests/test_serpent.py", line 810, in testRegular
    self.assertEqual("PrettyPrinter", data["__class__"])
                                      ~~~~^^^^^^^^^^^^^
KeyError: '__class__'
======================================================================
FAIL: testAttr (test_serpent.DataclassesTests.testAttr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/serpent-1.30.2/tests/test_serpent.py", line 1138, in testAttr
    self.assertDictEqual({"__class__": "InventoryItem", "name": "television", "quantity_on_hand": 5,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'__class__': 'InventoryItem', 'name': 'tel[72 chars]ped'} != {'name': 'television', 'unit_price': 1899.9[42 chars]ped'}
- {'__class__': 'InventoryItem',
-  'name': 'television',
? ^
+ {'name': 'television',
? ^
   'quantity_on_hand': 5,
   'unit_price': 1899.95,
   'untyped': 'untyped'}
======================================================================
FAIL: test_class (test_serpent.TestBasics.test_class)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/serpent-1.30.2/tests/test_serpent.py", line 495, in test_class
    self.assertEqual({'__class__': 'Class1', 'attr': 1}, data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'__class__': 'Class1', 'attr': 1} != {'attr': 1}
- {'__class__': 'Class1', 'attr': 1}
+ {'attr': 1}
======================================================================
FAIL: testChainMap (test_serpent.TestCollections.testChainMap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/serpent-1.30.2/tests/test_serpent.py", line 1081, in testChainMap
    self.assertEqual({'__class__': 'ChainMap', 'maps': [{'a': 1}, {'b': 2}, {'c': 3}]}, c2)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'__class__': 'ChainMap', 'maps': [{'a': 1}, {'b': 2}, {'c': 3}]} != {'maps': [{'a': 1}, {'b': 2}, {'c': 3}]}
- {'__class__': 'ChainMap', 'maps': [{'a': 1}, {'b': 2}, {'c': 3}]}
?  -------------------------
+ {'maps': [{'a': 1}, {'b': 2}, {'c': 3}]}
----------------------------------------------------------------------
Ran 76 tests in 0.046s
FAILED (failures=3, errors=2, skipped=2)
```

**Comment by irmen** [comment]
Ok figured it out. They messed with something, which broke serpent's generic object serializer:

https://docs.python.org/3.11/library/pickle.html#object.__getstate__ 
> Changed in version 3.11: Added the default implementation of the __getstate__() method in the [object](https://docs.python.org/3.11/library/functions.html#object) class.

**Comment by irmen** [comment]
dd77c8c06e387d3f981b094de2669cb7a030551f attempts to fix it but Pyro5 serialization tests still fail on certain cases.

**Comment by frantisekz** [comment]
@irmen thanks a lot for quick fix. It seems that the fix broke test_serpent.TestBasics.test_bytes (I can try and take a look, I am not very familiar with serpent's code base though :( and I don't see an obvious culprit in the commit) :

======================================================================
FAIL: test_bytes (test_serpent.TestBasics.test_bytes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/serpent-1.30.2/tests/test_serpent.py", line 429, in test_bytes
    self.assertEqual({'encoding': 'base64', 'data': 'YWJjZGVm'}, data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'encoding': 'base64', 'data': 'YWJjZGVm'} != {'data': 'YWJjZGVm', 'encoding': 'base64', '__class__': 'BytesWrapper'}
- {'data': 'YWJjZGVm', 'encoding': 'base64'}
+ {'__class__': 'BytesWrapper', 'data': 'YWJjZGVm', 'encoding': 'base64'}

**Comment by frantisekz** [comment]
Ahh, yeah, nevermind, I was using this against the 1.30 release. Works well on the 1.40, thanks!

**Comment by hroncok** [comment]
BTW see the fix that landed in jsonpickle: https://github.com/jsonpickle/jsonpickle/pull/396

**Comment by irmen** [comment]
changed the fix to be similar to the one mentioned above, seemed cleaner.
