### ISSUE TITLE
Support for a dictionary expression with a trailing comma?

### ISSUE THREAD

**Issue by vruusmann** [irmen/Serpent#7]
I am trying to use the Java version of Serpent for parsing the header of [NPY files] (http://docs.scipy.org/doc/numpy-dev/neps/npy-format.html).

A header looks something like this: `{'descr': '<i8', 'fortran_order': False, 'shape': (1,), }`. Serpent fails to parse this header string because of the trailing comma:
```
Exception in thread "main" net.razorvine.serpent.ParseException: invalid int character (at position 56; '...lse, 'shape': (1,), >>><<<}...')
        at net.razorvine.serpent.Parser.parse(Parser.java:60)
Caused by: net.razorvine.serpent.ParseException: invalid int character
        at net.razorvine.serpent.Parser.parseInt(Parser.java:320)
        at net.razorvine.serpent.Parser.parseSingle(Parser.java:310)
        at net.razorvine.serpent.Parser.parseExpr(Parser.java:79)
        at net.razorvine.serpent.Parser.parseKeyValue(Parser.java:190)
        at net.razorvine.serpent.Parser.parseKeyValueList(Parser.java:182)
        at net.razorvine.serpent.Parser.parseDict(Parser.java:261)
        at net.razorvine.serpent.Parser.parseCompound(Parser.java:99)
        at net.razorvine.serpent.Parser.parseExpr(Parser.java:77)
        at net.razorvine.serpent.Parser.parse(Parser.java:53)
        ... 3 more
```

I can solve this issue by applying the following patchfile, but from the grammar perspective, this is clearly a sub-optimal solution:
```
diff --git a/java/src/main/java/net/razorvine/serpent/Parser.java b/java/src/main/java/net/razorvine/serpent/Parser.java
index 8265531..1eec774 100644
--- a/java/src/main/java/net/razorvine/serpent/Parser.java
+++ b/java/src/main/java/net/razorvine/serpent/Parser.java
@@ -179,6 +179,10 @@ public class Parser
 		while(sr.hasMore() && sr.peek()==',')
 		{
 			sr.read();
+			sr.skipWhitespace();
+			if(sr.peek() == '}'){
+				break;
+			}
 			kvs.add(parseKeyValue(sr));
 		}
 		return kvs;
```

Does the Python grammar allow the trailing comma here?

If this is simply a quirk of the NPY file format, then I should probably replace `, }` at the end of the header string with `}`, and everything will be fine.

**Comment by irmen** [comment]
The Python syntax allows the trailing comma. It is a bit strange it appears in a computer generated data file though (one would expect the file outputter won't write superfluous characters).

However I will fix this in Serpent.

**Comment by irmen** [comment]
unrelated: those files aren't they supposed to be binary instead of text? :confused:

**Comment by vruusmann** [comment]
These NPY files are mostly binary files. The header string is embedded into it as an ASCII string.

Here's a quote from the linked document:
```
The next HEADER_LEN bytes form the header data describing the array’s format. It is an ASCII string which contains a Python literal expression of a dictionary.
```

**Comment by irmen** [comment]
fixed by teaching the parser about trailing comma's in expression lists and keyvalue lists
